# Generated by Django 5.2.17 on 2026-09-13 23:46

import django.db.models.functions.text
from django.db import migrations, models


def check_email_collisions(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    duplicates = (
        User.objects.using(schema_editor.connection.alias)
        .annotate(email_key=django.db.models.functions.text.Lower('email'))
        .values('email_key').annotate(count=models.Count('pk')).filter(count__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError('Case-equivalent user emails exist. Resolve identities before retrying this migration.')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userauthprovider'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(check_email_collisions, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='userauthprovider',
            name='accounts_us_user_id_cbcf01_idx',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
    ]
