# Generated by Django 6.0.3 on 2026-03-08 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('vegetation_variety', models.CharField(max_length=100)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('purpose', models.CharField(blank=True, choices=[('routine', 'Routine'), ('complaint driven', 'Complaint Driven'), ('target surveillance', 'Target Surveillance')], max_length=50, null=True)),
                ('sample_type', models.CharField(blank=True, choices=[('field', 'Field'), ('market', 'Market'), ('storage', 'Storage'), ('export', 'Export')], max_length=20, null=True)),
                ('processing_type', models.CharField(blank=True, choices=[('raw', 'Raw'), ('dried', 'Dried'), ('milled', 'Milled'), ('processed', 'Processed'), ('fermented', 'Fermented')], max_length=20, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('registered', 'Registered'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('analyzing', 'Analyzing'), ('recorded', 'Recorded'), ('completed', 'Completed')], max_length=20)),
                ('test_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('conducted_by', models.CharField(max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='samples.sample')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MycotoxinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intensity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dangerous', models.BooleanField(default=False)),
                ('threshold', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('test_method', models.CharField(blank=True, max_length=100, null=True)),
                ('sop_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycotoxin_results', to='samples.sample')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status'], name='samples_sam_status_431764_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['region'], name='samples_sam_region_9f9930_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['collection_date'], name='samples_sam_collect_92fed6_idx'),
        ),
    ]
