# Generated by Django 6.0.3 on 2026-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_mycotoxinresult_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycotoxinresult',
            name='concentration',
        ),
    ]
