# Generated by Django 6.0.3 on 2026-04-08 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_sync_is_detected_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['region', 'status'], name='samples_sam_region_1f244d_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['region', 'collection_date'], name='samples_sam_region_da04fc_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status', 'collection_date'], name='samples_sam_status_d79248_idx'),
        ),
    ]
