# Generated by Django 5.1.15 on 2026-04-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_sample_samples_sam_region_1f244d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycotoxinresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
