# Generated by Django 5.1.15 on 2026-04-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_mycotoxin_result_risk_level'),
    ]

    operations = [
    ]
