# Generated by Django 5.1.15 on 2026-04-26 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['province'], name='samples_sam_provinc_d3e417_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['vegetation_variety'], name='samples_sam_vegetat_5a7304_idx'),
        ),
    ]
