# Generated by Django 5.1.15 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_sample_samples_sam_provinc_d3e417_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'expires_at'], name='samples_ext_source_90db58_idx')],
            },
        ),
    ]
