# Generated by Django 5.2.17 on 2026-09-13 23:46

from django.db import migrations, models


def check_prediction_context(apps, schema_editor):
    Context = apps.get_model('samples', 'PredictionContext')
    valid = (
        (models.Q(latitude__isnull=True, longitude__isnull=True) | (
            models.Q(latitude__isnull=False, longitude__isnull=False)
            & models.Q(latitude__gte=-90, latitude__lte=90, longitude__gte=-180, longitude__lte=180)
        ))
        & (models.Q(moisture_pct__isnull=True) | models.Q(moisture_pct__gte=0, moisture_pct__lte=100))
        & (models.Q(soil_ph__isnull=True) | models.Q(soil_ph__gte=0, soil_ph__lte=14))
    )
    invalid = list(Context.objects.using(schema_editor.connection.alias).exclude(valid).values_list('pk', flat=True)[:20])
    if invalid:
        raise RuntimeError(f'Invalid prediction contexts; correct these IDs before retrying: {invalid}')


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_predictionestimate'),
    ]

    operations = [
        migrations.RunPython(check_prediction_context, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='externaldatacache',
            name='cache_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='externaldatacache',
            constraint=models.UniqueConstraint(fields=('source', 'cache_key'), name='external_cache_source_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='predictioncontext',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False), ('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='prediction_coordinates_valid'),
        ),
        migrations.AddConstraint(
            model_name='predictioncontext',
            constraint=models.CheckConstraint(condition=models.Q(('moisture_pct__isnull', True), models.Q(('moisture_pct__gte', 0), ('moisture_pct__lte', 100)), _connector='OR'), name='prediction_moisture_valid'),
        ),
        migrations.AddConstraint(
            model_name='predictioncontext',
            constraint=models.CheckConstraint(condition=models.Q(('soil_ph__isnull', True), models.Q(('soil_ph__gte', 0), ('soil_ph__lte', 14)), _connector='OR'), name='prediction_soil_ph_valid'),
        ),
    ]
