# Generated by Django 5.2.17 on 2026-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0020_sample_screening_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
