# Generated by Django 5.2.17 on 2026-09-13 23:48

from django.db import migrations, models


def align_legacy_data(apps, schema_editor):
    alias = schema_editor.connection.alias
    Sample = apps.get_model('samples', 'Sample')
    User = apps.get_model('accounts', 'User')
    Result = apps.get_model('samples', 'MycotoxinResult')
    AuditLog = apps.get_model('core', 'AuditLog')
    samples = Sample.objects.using(alias)
    conflicts = samples.exclude(sub_type__isnull=True).exclude(sub_type='').exclude(
        vegetation_variety=models.F('sub_type')
    )
    if conflicts.exists():
        raise RuntimeError('Conflicting legacy/subtype taxonomy exists. Resolve it before retrying; no values were discarded.')
    samples.filter(models.Q(sub_type__isnull=True) | models.Q(sub_type='')).update(sub_type=models.F('vegetation_variety'))
    usernames = dict(User.objects.using(alias).values_list('username', 'pk'))
    for sample in samples.filter(recorded_by__isnull=True).iterator():
        candidates = {pk for pk in [sample.updated_by_id, usernames.get(sample.collected_by)] if pk is not None}
        if len(candidates) == 1:
            samples.filter(pk=sample.pk).update(recorded_by_id=candidates.pop())
    for result in Result.objects.using(alias).all().iterator():
        before = {'risk_level': result.risk_level, 'eu_threshold_low': result.eu_threshold_low,
                  'eu_threshold_high': result.eu_threshold_high}
        low, high = result.eu_threshold_low, result.eu_threshold_high
        # Legacy 0010 encoded unavailable policies as 0/0 + unclassified.
        if result.risk_level == 'unclassified' and low == 0 and high == 0:
            low = high = None
        if result.value is None or low is None or high is None:
            risk = 'unclassified'
        elif result.value > high:
            risk = 'critical'
        elif result.value > low:
            risk = 'high'
        else:
            risk = 'detected' if result.value > 0 else 'safe'
        after = {'risk_level': risk, 'eu_threshold_low': low, 'eu_threshold_high': high}
        if before != after:
            AuditLog.objects.using(alias).create(
                action='risk_policy_repair', model_name='MycotoxinResult', object_id=str(result.pk),
                changes={'migration': 'samples.0021', 'before': before, 'after': after},
            )
            Result.objects.using(alias).filter(pk=result.pk).update(**after)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('samples', '0020_alter_externaldatacache_cache_key_and_more'),
        ('accounts', '0009_remove_userauthprovider_accounts_us_user_id_cbcf01_idx_and_more'),
        ('core', '0002_homepagecontent'),
    ]

    operations = [
        migrations.RunPython(align_legacy_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(
                condition=models.Q(sub_type__isnull=True) | models.Q(sub_type='')
                | models.Q(vegetation_variety=models.F('sub_type')), name='sample_taxonomy_consistent',
            ),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequence_number',
            field=models.IntegerField(db_default=0, db_index=True, default=0),
        ),
    ]
