"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-very-long-secret-key-for-jwt-tokens-32-chars-minimum!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Comma-separated list of allowed hosts, e.g. "mybackend.up.railway.app,api.mydomain.com"
_ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS.split(',') if h.strip()] if _ALLOWED_HOSTS else ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    'accounts',
    'samples',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use SQLite for development (default), PostgreSQL if explicitly configured
_DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')

if _DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'agriscan_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Cloudflare R2 Storage (S3-compatible)
# Documents: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
_R2_KEY = os.environ.get('R2_ACCESS_KEY_ID', '')
if _R2_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = _R2_KEY
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME', '')
    # R2 endpoint: https://<account-id>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL', '')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_REGION_NAME = 'auto'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False  # Public URLs without signed params
    # Optional: custom domain (Cloudflare R2 Public Domain)
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('R2_CUSTOM_DOMAIN', '')


# ─── Redis ────────────────────────────────────────────────────────────────────
# django-redis is used as the cache backend.
# Celery will also point its broker/result-backend at the same Redis URL.
# Set REDIS_URL in .env, e.g.:
#   REDIS_URL=redis://localhost:6379/0   (local)
#   REDIS_URL=redis://:password@host:6379/0  (production)

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Connection pool: reuse connections across requests
            'CONNECTION_POOL_KWARGS': {'max_connections': 50},
        },
        'KEY_PREFIX': 'agriscan',   # Namespace to avoid key collisions
        'TIMEOUT': 300,            # Default TTL: 5 minutes
    }
}

# Session storage in Redis (optional — falls back to DB if Redis is down)
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'

# ── How Celery will use this Redis ───────────────────────────────────────────
# Your teammate can copy these two lines into celery.py:
#
#   app.conf.broker_url = env('REDIS_URL')           # Task queue
#   app.conf.result_backend = env('REDIS_URL', 1)    # db=1 keeps results separate
#
# Then route a task like this from your Django view:
#
#   from myapp.tasks import run_prediction
#   run_prediction.delay(sample_id=42)   # fire-and-forget → Celery picks up from Redis
# ─────────────────────────────────────────────────────────────────────────────


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.User'

# In production, set CORS_ALLOWED_ORIGINS to comma-separated list of allowed frontend URLs
# e.g. "https://agriscan-pro.pages.dev,https://agriscan.yourdomain.com"
_CORS_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _CORS_ORIGINS:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _CORS_ORIGINS.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = True  # Development only

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.agriscan_exception_handler',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': "",
    'AUDIENCE': None,
    'ISSUER': None,
    'JSON_ENCODER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Structured Logging Configuration
import json
import logging.config
import sys

class StructuredFormatter(logging.Formatter):
    """JSON-structured logging formatter"""
    def format(self, record):
        log_obj = {
            'timestamp': self.formatTime(record),
            'level': record.levelname,
            'logger': record.name,
            'message': record.getMessage(),
        }
        if hasattr(record, 'request_id'):
            log_obj['request_id'] = record.request_id
        if record.exc_info:
            log_obj['exc_info'] = self.formatException(record.exc_info)
        if hasattr(record, '__dict__'):
            for key, value in record.__dict__.items():
                if key not in ('name', 'msg', 'args', 'created', 'filename', 'funcName', 'levelname', 'levelno', 'lineno', 'module', 'msecs', 'message', 'pathname', 'process', 'processName', 'relativeCreated', 'thread', 'threadName', 'exc_info', 'exc_text', 'stack_info', 'request_id'):
                    log_obj[key] = value
        return json.dumps(log_obj)

# Check if we're running tests
IS_TESTING = 'test' in sys.argv or 'pytest' in sys.argv[0]

# Build handlers dictionary - only include file handlers in production
_handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'verbose' if DEBUG else 'structured',
    },
}

# Add file handlers only if not testing
if not IS_TESTING:
    _logs_dir = BASE_DIR / 'logs'
    _logs_dir.mkdir(exist_ok=True)

    _handlers['app_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.environ.get('AGRISCAN_LOG_DIR', str(_logs_dir)) + '/app.log',
        'maxBytes': 10485760,  # 10MB
        'backupCount': 5,
        'formatter': 'structured',
    }
    _handlers['error_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.environ.get('AGRISCAN_LOG_DIR', str(_logs_dir)) + '/error.log',
        'maxBytes': 10485760,  # 10MB
        'backupCount': 5,
        'formatter': 'structured',
        'level': 'ERROR',
    }
    _handlers['audit_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.environ.get('AGRISCAN_LOG_DIR', str(_logs_dir)) + '/audit.log',
        'maxBytes': 10485760,  # 10MB
        'backupCount': 5,
        'formatter': 'structured',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            '()': StructuredFormatter,
        },
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': _handlers,
    'loggers': {
        'agriscan.samples': {
            'handlers': ['console'] + (['app_file', 'error_file'] if not IS_TESTING else []),
            'level': 'INFO',
            'propagate': False,
        },
        'agriscan.accounts': {
            'handlers': ['console'] + (['app_file', 'error_file'] if not IS_TESTING else []),
            'level': 'INFO',
            'propagate': False,
        },
        'agriscan.middleware': {
            'handlers': ['console'] + (['app_file', 'error_file'] if not IS_TESTING else []),
            'level': 'INFO',
            'propagate': False,
        },
        'agriscan.audit': {
            'handlers': ['console'] + (['audit_file'] if not IS_TESTING else []),
            'level': 'INFO',
            'propagate': False,
        },
    },
}
