"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import logging
import logging.config
import os
import sys
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path
from typing import cast

from django.core.exceptions import ImproperlyConfigured

from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local backend/.env values without overriding real deployment secrets.
load_dotenv(BASE_DIR / ".env", override=False)

# Default auto field to avoid models.W042 warnings (Django 3.2+)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DEFAULT_LOCAL_ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
AWS_PLATFORM_ALLOWED_HOST_PATTERNS = [
    ".elasticbeanstalk.com",
    ".compute.amazonaws.com",
]


def build_allowed_hosts(raw_hosts: str, *, debug: bool) -> list[str]:
    """Build ALLOWED_HOSTS and keep AWS platform health-check hosts reachable."""
    if raw_hosts:
        hosts = [h.strip() for h in raw_hosts.split(",") if h.strip()]
        if "*" not in hosts:
            for host in [
                *DEFAULT_LOCAL_ALLOWED_HOSTS,
                *AWS_PLATFORM_ALLOWED_HOST_PATTERNS,
            ]:
                if host not in hosts:
                    hosts.append(host)
        return hosts

    if not debug:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS environment variable is required in production"
        )

    return DEFAULT_LOCAL_ALLOWED_HOSTS.copy()


# QUICK-START DEVELOPMENT SETTINGS
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("SECRET_KEY environment variable is required in production")
    SECRET_KEY = "insecure-dev-key"

# Comma-separated list of allowed hosts
_ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = build_allowed_hosts(_ALLOWED_HOSTS, debug=DEBUG)


# Trusted proxies for X-Forwarded-For validation
TRUSTED_PROXIES = [p.strip() for p in os.environ.get("TRUSTED_PROXIES", "").split(",") if p.strip()]

# Server-side LLM provider config for public health dashboard summaries.
LLM_SUMMARY_ENDPOINT = os.environ.get("LLM_SUMMARY_ENDPOINT", "")
LLM_SUMMARY_MODEL = os.environ.get("LLM_SUMMARY_MODEL", "")
LLM_SUMMARY_API_KEY = os.environ.get("LLM_SUMMARY_API_KEY", "")
LLM_SUMMARY_TIMEOUT_SECONDS = int(os.environ.get("LLM_SUMMARY_TIMEOUT_SECONDS", "20"))
LLM_SUMMARY_MAX_OUTPUT_TOKENS = int(os.environ.get("LLM_SUMMARY_MAX_OUTPUT_TOKENS", "1024"))

# NASA POWER environmental data for dashboard kinetics.
NASA_POWER_TIMEOUT_SECONDS = int(os.environ.get("NASA_POWER_TIMEOUT_SECONDS", "20"))
NASA_POWER_MAX_DAYS = int(os.environ.get("NASA_POWER_MAX_DAYS", "14"))
NASA_POWER_CACHE_TTL_HOURS = int(os.environ.get("NASA_POWER_CACHE_TTL_HOURS", "24"))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "storages",
    "drf_spectacular",
    "core.apps.CoreConfig",
    "accounts",
    "samples",
    "notifications",
]

_HAS_WHITENOISE = find_spec("whitenoise") is not None

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    *(
        ["whitenoise.middleware.WhiteNoiseMiddleware"] if _HAS_WHITENOISE else []
    ),  # Serve static files (Django admin, etc.) when WhiteNoise is installed
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.RateLimitMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Keep test detection near DB/cache configuration so both can share it.
IS_TESTING = "test" in sys.argv or "pytest" in sys.argv[0]

# Use SQLite for development (default), PostgreSQL when explicitly configured.
# During tests, default to SQLite unless TEST_DB_ENGINE is explicitly set.
_db_engine = os.environ.get("DB_ENGINE", "sqlite").strip().lower()
_test_db_engine = os.environ.get("TEST_DB_ENGINE", "sqlite").strip().lower()
_active_db_engine = _test_db_engine if IS_TESTING else _db_engine

if _active_db_engine == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "agriscan_db"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    # SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ─── AWS S3 Storage ───────────────────────────────────────────────────────────
# If running on EB with an Instance Profile, set these to None or leave unset in environment.
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "ap-southeast-1")
AWS_S3_FILE_OVERWRITE = False  # Auto-append suffix if name collision
AWS_DEFAULT_ACL = None  # Use bucket policy instead of ACL
AWS_S3_SIGNATURE_VERSION = "s3v4"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "location": "uploads/raw",
            "file_overwrite": False,
            "access_key": AWS_ACCESS_KEY_ID,  # Will be None if not provided
            "secret_key": AWS_SECRET_ACCESS_KEY,  # Will be None if not provided
        },
    },
    # WhiteNoise serves static files (Django admin CSS/JS) with gzip + cache headers
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ─── Async Tasks / Redis / Cache ─────────────────────────────────────────────
# ASYNC_TASKS_ENABLED=False (default): app runs without Redis or a Celery worker.
#   Cache → LocMemCache  |  Tasks → synchronous / inline execution
# ASYNC_TASKS_ENABLED=True: requires Redis (REDIS_URL) and a running Celery worker.
#   Cache → django-redis  |  Tasks → dispatched to Celery


def env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean environment variable robustly.

    Treats '1', 'true', 'yes', 'on' (case-insensitive) as True.
    Returns *default* when the variable is not set.
    """
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


ASYNC_TASKS_ENABLED: bool = env_bool("ASYNC_TASKS_ENABLED", default=False)

# REDIS_URL defaults to empty string so that the absence of the env var is
# unambiguous.  When ASYNC_TASKS_ENABLED=False we never need a real Redis URL.
REDIS_URL: str = os.getenv("REDIS_URL", "").strip()

# Use LocMemCache when: async tasks are disabled, no Redis URL, tests are
# running, or the operator explicitly requests it via USE_LOCAL_MEMORY_CACHE.
USE_LOCAL_MEMORY_CACHE: bool = (
    IS_TESTING
    or not ASYNC_TASKS_ENABLED
    or not REDIS_URL
    or env_bool("USE_LOCAL_MEMORY_CACHE", default=False)
)

# ElastiCache (and any TLS Redis) use rediss:// scheme — auto-enable SSL options.
# Set REDIS_SSL_CERT_REQS=required (default) for ACM-signed certs (AWS ElastiCache);
# set to 'none' only if using self-signed or dev certs.
_REDIS_USE_SSL: bool = REDIS_URL.startswith("rediss://")
_REDIS_SSL_CERT_REQS: str | None = (
    os.environ.get("REDIS_SSL_CERT_REQS", "required") if _REDIS_USE_SSL else None
)

_redis_pool_kwargs: dict[str, object] = {"max_connections": 50}
if _REDIS_SSL_CERT_REQS is not None:
    _redis_pool_kwargs["ssl_cert_reqs"] = _REDIS_SSL_CERT_REQS

if USE_LOCAL_MEMORY_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "agriscan-local-cache",
            "KEY_PREFIX": "agriscan",
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": _redis_pool_kwargs,
                "SOCKET_CONNECT_TIMEOUT": 3,  # Fail fast if Redis is unreachable
                "SOCKET_TIMEOUT": 3,
            },
            "KEY_PREFIX": "agriscan",  # Namespace to avoid key collisions
            "TIMEOUT": 300,  # Default TTL: 5 minutes
        }
    }

# Session storage in Redis (optional — falls back to DB if Redis is down)
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'

# ─── Celery ───────────────────────────────────────────────────────────────────
# Task 3: When ASYNC_TASKS_ENABLED=False, use an in-memory broker so that
# importing core.celery never fails and tasks run eagerly/synchronously.
# When ASYNC_TASKS_ENABLED=True, connect to Redis as the broker/result-backend.
if not ASYNC_TASKS_ENABLED:
    CELERY_TASK_ALWAYS_EAGER = True       # run tasks inline (synchronous)
    CELERY_TASK_EAGER_PROPAGATES = True   # propagate exceptions instead of swallowing
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
else:
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

    # ElastiCache TLS — pass SSL options to Celery broker and result backend
    if _REDIS_USE_SSL:
        _celery_ssl_opts = {"ssl_cert_reqs": _REDIS_SSL_CERT_REQS}
        CELERY_BROKER_USE_SSL = _celery_ssl_opts
        CELERY_REDIS_BACKEND_USE_SSL = _celery_ssl_opts

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULE = {
    "prune-expired-nasa-power-cache": {
        "task": "samples.tasks.prune_expired_nasa_power_cache",
        "schedule": timedelta(hours=1),
    },
}
# ─────────────────────────────────────────────────────────────────────────────


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic output directory for EB/nginx

AUTH_USER_MODEL = "accounts.User"

# ─── CORS ─────────────────────────────────────────────────────────────────────
# Set CORS_ALLOWED_ORIGINS to a comma-separated list of allowed frontend URLs in
# production, e.g. "https://agriscan-pro.pages.dev,https://agriscan.yourdomain.com".
# Local/CloudFront defaults are always included so that dev environments work
# out-of-the-box.

CORS_ALLOW_ALL_ORIGINS = DEBUG or os.environ.get("CORS_ALLOW_ALL") == "True"
CORS_ALLOW_CREDENTIALS = True

_LOCAL_ORIGINS = [
    "https://d27isnumffqap.cloudfront.net",
]
if DEBUG:
    _LOCAL_ORIGINS += [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
    ]
_ENV_ORIGINS = [
    o.strip()
    for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if o.strip()
]
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(_ENV_ORIGINS + _LOCAL_ORIGINS))  # dedupe, order-preserving

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
]

FORCE_SSL = os.environ.get("FORCE_SSL", "False") == "True"

JWT_USE_HTTPONLY_REFRESH_COOKIE = (
    os.environ.get("JWT_USE_HTTPONLY_REFRESH_COOKIE", "True") == "True"
)
JWT_REFRESH_COOKIE_NAME = os.environ.get("JWT_REFRESH_COOKIE_NAME", "refresh_token")
JWT_REFRESH_COOKIE_PATH = os.environ.get("JWT_REFRESH_COOKIE_PATH", "/api/accounts/")
JWT_REFRESH_COOKIE_MAX_AGE = int(
    os.environ.get("JWT_REFRESH_COOKIE_MAX_AGE", str(7 * 24 * 60 * 60))
)
JWT_REFRESH_COOKIE_SECURE = (
    os.environ.get("JWT_REFRESH_COOKIE_SECURE", "False" if DEBUG else "True") == "True"
)
JWT_REFRESH_COOKIE_SAMESITE = os.environ.get(
    "JWT_REFRESH_COOKIE_SAMESITE", "Lax" if DEBUG else "None"
)
GOOGLE_OAUTH_STATE_TTL_SECONDS = int(
    os.environ.get("GOOGLE_OAUTH_STATE_TTL_SECONDS", "300")
)


def validate_refresh_cookie_security_config(
    *,
    debug: bool,
    refresh_cookie_samesite: str,
    refresh_cookie_secure: bool,
    force_ssl: bool,
) -> None:
    """
    Reject direct-HTTP development combinations that cannot support SameSite=None cookies.

    Production is allowed to keep Secure cookies with FORCE_SSL disabled because
    CloudFront terminates browser-facing HTTPS before forwarding to EB over HTTP.
    """
    if (
        debug
        and refresh_cookie_samesite.lower() == "none"
        and refresh_cookie_secure
        and not force_ssl
    ):
        raise ImproperlyConfigured(
            "JWT refresh cookies cannot use SameSite=None with Secure=True while "
            "DEBUG=True and FORCE_SSL=False. Use HTTPS locally, enable FORCE_SSL, "
            "or switch SameSite/Secure to a local-safe combination."
        )


validate_refresh_cookie_security_config(
    debug=DEBUG,
    refresh_cookie_samesite=JWT_REFRESH_COOKIE_SAMESITE,
    refresh_cookie_secure=JWT_REFRESH_COOKIE_SECURE,
    force_ssl=FORCE_SSL,
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "core.exceptions.agriscan_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "AgriScan Pro API",
    "DESCRIPTION": "API for Mycotoxin Analysis and Sample Management",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Production Security Enforcements (Enforced when DEBUG=False)
if not DEBUG:
    # Set FORCE_SSL environment variable to True to enable HTTPS redirection
    # IMPORTANT: Only enable this if your Load Balancer or Proxy handles SSL correctly.
    # On AWS EB direct domains, forcing SSL will break connectivity unless an ALB with a cert is used.
    SECURE_SSL_REDIRECT = FORCE_SSL

    # If we are not forcing SSL, ensure we don't send HSTS headers either
    # which would force the browser to use HTTPS even if we don't redirect.
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    else:
        SECURE_HSTS_SECONDS = 0

    # Trust the X-Forwarded-Proto header from standard proxies like ALB/CloudFront
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Support CloudFront-specific header as well
    USE_X_FORWARDED_PORT = True
    SECURE_REFERRER_POLICY = "same-origin"


# Structured Logging Configuration


class StructuredFormatter(logging.Formatter):
    """JSON-structured logging formatter"""

    def format(self, record):
        log_obj = {
            "timestamp": self.formatTime(record),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        request_id = record.__dict__.get("request_id")
        if request_id is not None:
            log_obj["request_id"] = request_id
        if record.exc_info:
            log_obj["exc_info"] = self.formatException(record.exc_info)
        if hasattr(record, "__dict__"):
            for key, value in record.__dict__.items():
                if key not in (
                    "name",
                    "msg",
                    "args",
                    "created",
                    "filename",
                    "funcName",
                    "levelname",
                    "levelno",
                    "lineno",
                    "module",
                    "msecs",
                    "message",
                    "pathname",
                    "process",
                    "processName",
                    "relativeCreated",
                    "thread",
                    "threadName",
                    "exc_info",
                    "exc_text",
                    "stack_info",
                    "request_id",
                ):
                    log_obj[key] = value
        return json.dumps(log_obj)


# Check if we're running tests

# Build handlers dictionary - only include file handlers in production
_handlers: dict[str, dict[str, object]] = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "verbose" if DEBUG else "structured",
    },
}

# Add file handlers only if not testing AND if we're not for sure on EB/Production to avoid permission errors
# In production, we rely on console logging which EB/CloudWatch captures automatically.
_ENABLE_FILE_LOGGING = not IS_TESTING and (
    DEBUG or os.environ.get("ENABLE_FILE_LOGGING") == "True"
)

_logs_dir = Path(os.environ.get("AGRISCAN_LOG_DIR", str(BASE_DIR / "logs")))

if _ENABLE_FILE_LOGGING:
    try:
        _logs_dir.mkdir(exist_ok=True)
    except PermissionError:
        _ENABLE_FILE_LOGGING = False

if _ENABLE_FILE_LOGGING:
    _handlers["app_file"] = cast(
        dict[str, object],
        {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.environ.get("AGRISCAN_LOG_DIR", str(_logs_dir)) + "/app.log",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
            "formatter": "structured",
        },
    )
    _handlers["error_file"] = cast(
        dict[str, object],
        {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.environ.get("AGRISCAN_LOG_DIR", str(_logs_dir))
            + "/error.log",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
            "formatter": "structured",
            "level": "ERROR",
        },
    )
    _handlers["audit_file"] = cast(
        dict[str, object],
        {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.environ.get("AGRISCAN_LOG_DIR", str(_logs_dir))
            + "/audit.log",
            "maxBytes": 10485760,  # 10MB
            "backupCount": 5,
            "formatter": "structured",
        },
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "()": StructuredFormatter,
        },
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": _handlers,
    "loggers": {
        "agriscan.samples": {
            "handlers": ["console"]
            + (["app_file", "error_file"] if _ENABLE_FILE_LOGGING else []),
            "level": "INFO",
            "propagate": False,
        },
        "agriscan.accounts": {
            "handlers": ["console"]
            + (["app_file", "error_file"] if _ENABLE_FILE_LOGGING else []),
            "level": "INFO",
            "propagate": False,
        },
        "agriscan.middleware": {
            "handlers": ["console"]
            + (["app_file", "error_file"] if _ENABLE_FILE_LOGGING else []),
            "level": "INFO",
            "propagate": False,
        },
        "agriscan.audit": {
            "handlers": ["console"] + (["audit_file"] if _ENABLE_FILE_LOGGING else []),
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ─── Email Configuration ─────────────────────────────────────────────────────
# Using environment variables for sensitive credentials.
# In production, set these in your hosting environment (e.g., EB, Railway, etc.)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if os.environ.get("EMAIL_HOST_USER")
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", f"AgriScan Pro <{EMAIL_HOST_USER}>"
)

# ─── Administrative & Access Controls ──────────────────────────────────────────
# A list of emails that automatically receive the 'admin' role upon Google login.
# Format: "admin1@example.com,admin2@example.com" in .env or EB properties.
INITIAL_ADMIN_EMAILS = [
    email.strip()
    for email in os.environ.get("INITIAL_ADMIN_EMAILS", "").split(",")
    if email.strip()
]

# The minimum role required for a user to be granted access to the Monitor.
# Available roles: admin, head_researcher, researcher, research_assistant, user
MONITOR_ACCESS_MIN_ROLE = os.environ.get(
    "MONITOR_ACCESS_MIN_ROLE", "research_assistant"
)

# ─── Vercel KV (Redis) for Monitor Sync ───────────────────────────────────────
KV_REST_API_URL = os.environ.get("KV_REST_API_URL", "")
KV_REST_API_TOKEN = os.environ.get("KV_REST_API_TOKEN", "")
