CREATE TABLE IF NOT EXISTS "sample" (
	"sample_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"region_id" INTEGER NOT NULL,
	"pickup_date" INTEGER NOT NULL,
	"variety_id" INTEGER NOT NULL,
	"processing_id" INTEGER NOT NULL,
	"test_id" INTEGER NOT NULL,
	"state_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("sample_id")
);




CREATE TABLE IF NOT EXISTS "reigon" (
	"region_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"region_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("region_id")
);




CREATE TABLE IF NOT EXISTS "province" (
	"province_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"province_name" VARCHAR(255) NOT NULL,
	"district_name" VARCHAR(255) NOT NULL,
	"region_id" INTEGER NOT NULL,
	PRIMARY KEY("province_id")
);




CREATE TABLE IF NOT EXISTS "mycotoxin" (
	"mycotoxin_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"toxin_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("mycotoxin_id")
);


CREATE INDEX "mycotoxin_index_0"
ON "mycotoxin" ();

CREATE TABLE IF NOT EXISTS "toxin_result" (
	"toxin_result_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"toxin_value" INTEGER NOT NULL,
	"above_the_limit" BOOLEAN NOT NULL,
	"mycotoxin_id" INTEGER NOT NULL,
	"test_id" INTEGER NOT NULL,
	PRIMARY KEY("toxin_result_id")
);




CREATE TABLE IF NOT EXISTS "user_profile" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"role" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "mycotoxin_limit" (
	"mycotoxin_limit_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"processing_id" INTEGER NOT NULL,
	"mycotoxin_id" INTEGER NOT NULL,
	"limit_value" INTEGER NOT NULL,
	PRIMARY KEY("mycotoxin_limit_id")
);




CREATE TABLE IF NOT EXISTS "state" (
	"state_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"state_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("state_id")
);




CREATE TABLE IF NOT EXISTS "test_result" (
	"test_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"test_result" VARCHAR(255) NOT NULL,
	PRIMARY KEY("test_id")
);




CREATE TABLE IF NOT EXISTS "processingtype" (
	"processing_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"processing_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("processing_id")
);




CREATE TABLE IF NOT EXISTS "variety" (
	"variety_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"variety_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("variety_id")
);




CREATE TABLE IF NOT EXISTS "process_log" (
	"log_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"timestamp" INTEGER NOT NULL,
	"state_id" INTEGER NOT NULL,
	"sample_id" INTEGER NOT NULL,
	"user_id" INTEGER NOT NULL,
	PRIMARY KEY("log_id")
);



ALTER TABLE "sample"
ADD FOREIGN KEY("region_id") REFERENCES "reigon"("region_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sample"
ADD FOREIGN KEY("sample_id") REFERENCES "process_log"("log_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "process_log"
ADD FOREIGN KEY("state_id") REFERENCES "state"("state_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "process_log"
ADD FOREIGN KEY("user_id") REFERENCES "user_profile"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sample"
ADD FOREIGN KEY("test_id") REFERENCES "test_result"("test_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sample"
ADD FOREIGN KEY("processing_id") REFERENCES "processingtype"("processing_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sample"
ADD FOREIGN KEY("variety_id") REFERENCES "variety"("variety_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "province"
ADD FOREIGN KEY("region_id") REFERENCES "reigon"("region_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "processingtype"
ADD FOREIGN KEY("processing_id") REFERENCES "mycotoxin_limit"("processing_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "test_result"
ADD FOREIGN KEY("test_id") REFERENCES "toxin_result"("test_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "mycotoxin"
ADD FOREIGN KEY("mycotoxin_id") REFERENCES "mycotoxin_limit"("mycotoxin_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "mycotoxin"
ADD FOREIGN KEY("mycotoxin_id") REFERENCES "toxin_result"("mycotoxin_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;